name: LU_compute
channels:
  - conda-forge
  - defaults
dependencies:
- mdtraj
- python=3.6
- numpy=1.13
- scipy=1.0
- pandas=0.21
- matplotlib=2.1
- notebook=5.2
- jupyter=1.0
- anaconda
- pip:
  - codacy-coverage>=1.3.3
  - mem_top==0.1.5
  - atari_py>=0.0.18
  - cmake==0.6.0
  - tensorflow>=1.0.0
  - Keras>=1.2.2,<2.0.0
  - "--editable=git+https://github.com/openai/gym.git#egg=gym[all]"

 
